local Tunnel = module("vrp","lib/Tunnel")
local Proxy = module("vrp","lib/Proxy")
vRP = Proxy.getInterface("vRP")
vRPclient = Tunnel.getInterface("vRP")

AddEventHandler("gmz:blips", function(parameters, cb)
	local result = load("return "..parameters)
	local _, add = pcall(result)
    cb(add)
end)